
package GUI;

import Base_Datos.BDGestionarClientes;
import Entidades.Cliente;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;


public class JIFGestionCliente extends javax.swing.JInternalFrame {
    
    DefaultListModel listmodeloCliente = new DefaultListModel();
    boolean estEditando = false;
    int index = -1;
    public JIFGestionCliente() throws Exception {
        initComponents();
        this.estEditando = false;
        this.cargarData();
        this.HabilitarDesabilitarTF(false);
        this.habilitarBotonesDerecha(false);
        this.habilitarBotonesIzquierda(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        TFNombre = new javax.swing.JTextField();
        TFApellido = new javax.swing.JTextField();
        TFDni = new javax.swing.JTextField();
        TFTelefono = new javax.swing.JTextField();
        TFDireccion = new javax.swing.JTextField();
        TFCorreo = new javax.swing.JTextField();
        BTGuardar = new javax.swing.JButton();
        BTCancelar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        BTEliminar = new javax.swing.JButton();
        BTMostrar = new javax.swing.JButton();
        BTEditar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        JLCliente = new javax.swing.JList<>();
        jPanel3 = new javax.swing.JPanel();
        BTNuevo = new javax.swing.JButton();
        BTSalir = new javax.swing.JButton();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Agregar Cliente"));

        jLabel1.setText("Apellido");

        jLabel2.setText("Nombre");

        jLabel3.setText("DNI");

        jLabel4.setText("Telefono");

        jLabel5.setText("Direccion");

        jLabel6.setText("Correo");

        TFDni.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TFDniKeyTyped(evt);
            }
        });

        TFTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TFTelefonoKeyTyped(evt);
            }
        });

        BTGuardar.setText("Guardar");
        BTGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTGuardarActionPerformed(evt);
            }
        });

        BTCancelar.setText("Cancelar");
        BTCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(BTGuardar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                        .addComponent(BTCancelar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(TFDni, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(TFTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(TFNombre))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(TFCorreo))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(TFApellido))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(TFDireccion)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel2))
                    .addComponent(TFNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(TFApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(TFDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(TFTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(TFDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(TFCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTGuardar)
                    .addComponent(BTCancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Listado Cliente"));

        BTEliminar.setText("Eliminar");
        BTEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTEliminarActionPerformed(evt);
            }
        });

        BTMostrar.setText("Mostrar");
        BTMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTMostrarActionPerformed(evt);
            }
        });

        BTEditar.setText("Editar");
        BTEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTEditarActionPerformed(evt);
            }
        });

        JLCliente.setModel(this.listmodeloCliente);
        JLCliente.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                JLClienteValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(JLCliente);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(BTMostrar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BTEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(BTEditar)
                .addContainerGap(8, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jScrollPane2)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTEliminar)
                    .addComponent(BTMostrar)
                    .addComponent(BTEditar))
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BTNuevo.setText("Nuevo");
        BTNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNuevoActionPerformed(evt);
            }
        });
        jPanel3.add(BTNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        BTSalir.setText("Salir");
        BTSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTSalirActionPerformed(evt);
            }
        });
        jPanel3.add(BTSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(544, 20, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTGuardarActionPerformed
        Cliente objC = new Cliente();
        BDGestionarClientes gestC = new BDGestionarClientes();
        try{
            validarCliente();
            objC.setApellido(this.TFApellido.getText());
            objC.setNombre(this.TFNombre.getText());
            objC.setDni(this.TFDni.getText());
            objC.setCorreo(this.TFCorreo.getText());
            objC.setDireccion(this.TFDireccion.getText());
            objC.setTelef(this.TFTelefono.getText());
            
            if(!this.estEditando){
            
               int id = gestC.crear(objC);
               objC.setId(id);
               System.out.println("id: " + id);
               this.listmodeloCliente.addElement(objC);
            
            }
            else{
               
                Cliente cliEdit = (Cliente) this.listmodeloCliente.get(this.index);
                gestC.actualizar(cliEdit.getId(), objC);
                this.listmodeloCliente.set(index, objC);
                this.BTNuevo.setEnabled(true);
            
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
            this.BTCancelarActionPerformed(evt);
        }finally{
            limpiar();
            this.HabilitarDesabilitarTF(false);
            this.habilitarBotonesDerecha(false);
            this.habilitarBotonesIzquierda(false);
            this.estEditando = false;
            this.index = -1;
        }
    }//GEN-LAST:event_BTGuardarActionPerformed

    private void TFTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFTelefonoKeyTyped
        int cantLetras = this.TFTelefono.getText().length();
        char c = evt.getKeyChar();
        validarNumero(evt, 9, cantLetras);
        if (this.TFTelefono.getText().length() == 0 && c != '9') {
            evt.consume();
        }
    }//GEN-LAST:event_TFTelefonoKeyTyped

    private void TFDniKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFDniKeyTyped
        int cantLetras = this.TFDni.getText().length();
        validarNumero(evt, 8, cantLetras);
    }//GEN-LAST:event_TFDniKeyTyped

    private void BTMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTMostrarActionPerformed
        this.HabilitarDesabilitarTF(false);
        this.BTGuardar.setEnabled(false);
        this.BTNuevo.setEnabled(false);
        this.habilitarBotonesDerecha(false);
        this.index = this.JLCliente.getSelectedIndex();
        this.setClientes(index);
        this.index = -1;
    }//GEN-LAST:event_BTMostrarActionPerformed

    private void BTEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTEditarActionPerformed
        this.index = this.JLCliente.getSelectedIndex();
        if(this.index <0){
            return; 
        }
        this.setClientes(index);
        this.HabilitarDesabilitarTF(true);
        this.habilitarBotonesIzquierda(true);
        this.BTNuevo.setEnabled(false);
        this.habilitarBotonesDerecha(false);
        this.estEditando = true;
        
    }//GEN-LAST:event_BTEditarActionPerformed

    private void BTEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTEliminarActionPerformed
        int respuesta  = JOptionPane.showConfirmDialog(null, "¿Estas seguro que deseas eliminar?", "Mensaje de Confirmación", JOptionPane.YES_NO_OPTION);
        this.index = this.JLCliente.getSelectedIndex();
        Object objC = this.JLCliente.getSelectedValue();
        Cliente cliente = (Cliente) objC;
        //Cliente.setEstado(0);
        if(objC == null){
            return;
        }
        try{
            
            if(respuesta == 0){
                
                this.listmodeloCliente.remove(index);
                BDGestionarClientes gstC = new BDGestionarClientes();
                this.index = cliente.getId();
                gstC.eliminar(this.index);
                
            }
        }catch(Exception e){
            System.out.println("Error: " + e.getMessage());
        }finally{
            this.index = -1;
            this.habilitarBotonesDerecha(false);
            this.habilitarBotonesIzquierda(false);
            this.limpiar();
        }
        
    }//GEN-LAST:event_BTEliminarActionPerformed

    private void BTCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTCancelarActionPerformed
        this.limpiar();
        this.index = -1;
        this.estEditando = false;
        this.habilitarBotonesIzquierda(false);
        this.habilitarBotonesDerecha(false);
        this.HabilitarDesabilitarTF(false);
        this.BTNuevo.setEnabled(true);
    }//GEN-LAST:event_BTCancelarActionPerformed

    private void BTSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTSalirActionPerformed
        dispose();
    }//GEN-LAST:event_BTSalirActionPerformed

    private void BTNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNuevoActionPerformed
        this.habilitarBotonesIzquierda(true);
        this.HabilitarDesabilitarTF(true);
        this.limpiar();
    }//GEN-LAST:event_BTNuevoActionPerformed

    private void JLClienteValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_JLClienteValueChanged
        this.HabilitarDesabilitarTF(false);
        this.habilitarBotonesIzquierda(false);
        this.habilitarBotonesDerecha(true);
        this.BTCancelar.setEnabled(true);
    }//GEN-LAST:event_JLClienteValueChanged
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTCancelar;
    private javax.swing.JButton BTEditar;
    private javax.swing.JButton BTEliminar;
    private javax.swing.JButton BTGuardar;
    private javax.swing.JButton BTMostrar;
    private javax.swing.JButton BTNuevo;
    private javax.swing.JButton BTSalir;
    private javax.swing.JList<String> JLCliente;
    private javax.swing.JTextField TFApellido;
    private javax.swing.JTextField TFCorreo;
    private javax.swing.JTextField TFDireccion;
    private javax.swing.JTextField TFDni;
    private javax.swing.JTextField TFNombre;
    private javax.swing.JTextField TFTelefono;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables

    private void limpiar() {
        this.TFApellido.setText("");
        this.TFNombre.setText("");
        this.TFDni.setText("");
        this.TFTelefono.setText("");
        this.TFDireccion.setText("");
        this.TFCorreo.setText("");
    }
    
    private void validarNumero(java.awt.event.KeyEvent evt, int tam, int cantLetras){
        char c = evt.getKeyChar();
        try{
            if (!Character.isDigit(c) || cantLetras >= tam) {
            evt.consume(); // Evita que se ingrese el carácter si no es un dígito o si ya hay 9 dígitos
            }
        }catch(Exception e){
            e.getMessage();
        }
    }
    
    private void validarCliente() throws Exception{
        try {
            
            if(this.TFApellido.getText().isEmpty()){
                throw new Exception("Ingrese sus apellidos por favor");
            }
            if(this.TFNombre.getText().isEmpty()){
                throw new Exception("Ingrese su/s nombre/s");
            }
            if(!(this.TFDni.getText().isEmpty())){
                if(this.TFDni.getText().length() != 8){
                    throw new Exception("DNI incorrecto");
                }
            }else{
                throw new Exception("Ingrese su DNI");
            }
            
            if(this.TFTelefono.getText().length() != 9){
                throw new Exception("Telefono incorrecto");
            }                                 
            
        } catch (Exception e){
            throw e; 
        }
    }
    
    private void setClientes(int indx){
        Cliente objC = (Cliente) this.listmodeloCliente.getElementAt(indx);
        BDGestionarClientes bdC = new BDGestionarClientes();
        try{
            objC = (Cliente) bdC.get(objC.getId());
        
            this.TFApellido.setText(objC.getApellido());
            this.TFNombre.setText(objC.getNombre());
            this.TFDni.setText(objC.getDni());
            this.TFTelefono.setText(objC.getTelef());
            this.TFDireccion.setText(objC.getDireccion());
            this.TFCorreo.setText(objC.getCorreo());
        }catch(Exception e){
            System.out.println("ERROR: " + e.getMessage());
        }
    }
    
    private void HabilitarDesabilitarTF(boolean res){
        this.TFApellido.setEnabled(res);
        this.TFNombre.setEnabled(res);
        this.TFDni.setEnabled(res);
        this.TFDireccion.setEnabled(res);
        this.TFTelefono.setEnabled(res);
        this.TFCorreo.setEnabled(res);
    }
    
    private void habilitarBotonesIzquierda(boolean res){
        this.BTCancelar.setEnabled(res);
        this.BTGuardar.setEnabled(res);
    }
    
    private void habilitarBotonesDerecha(boolean res){
            this.BTMostrar.setEnabled(res);
            this.BTEditar.setEnabled(res);
            this.BTEliminar.setEnabled(res);
    }
    
    private void cargarData() throws Exception {
        try{
            BDGestionarClientes gestC = new BDGestionarClientes();
            List listado = gestC.listar();
            for(Object object : listado){
                Cliente c = (Cliente) object;
                this.listmodeloCliente.addElement(c);
            }
            System.out.println("Listado Exitoso");
        }catch(Exception e){
            throw e;
        }
    }
}
