/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/MDIApplication.java to edit this template
 */
package GUI;

import Base_Datos.Conexion;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author LENOVO
 */
public class MDI_Principal extends javax.swing.JFrame {

    /**
     * Creates new form NewMDIApplication
     */
    private JIFListadoCliente lisCliente = null;
    private JIFGestionCliente gstCliente = null;
    private JIFPapeleraEliminados lisRestaurar = null;
    public MDI_Principal() {
        initComponents();
        //testconectar(); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        FMExit = new javax.swing.JMenu();
        exitMenuItem = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        JMCliente = new javax.swing.JMenuItem();
        JMListadoC = new javax.swing.JMenuItem();
        JMPapelera = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        JMListadoP = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        JMListadoV = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        FMExit.setMnemonic('f');
        FMExit.setText("File");
        FMExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FMExitActionPerformed(evt);
            }
        });

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        FMExit.add(exitMenuItem);

        menuBar.add(FMExit);

        editMenu.setMnemonic('e');
        editMenu.setText("Gestion Cliente");
        editMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editMenuActionPerformed(evt);
            }
        });

        JMCliente.setText("Formulario");
        JMCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMClienteActionPerformed(evt);
            }
        });
        editMenu.add(JMCliente);

        JMListadoC.setText("Listado");
        JMListadoC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMListadoCActionPerformed(evt);
            }
        });
        editMenu.add(JMListadoC);

        JMPapelera.setText("Papelera");
        JMPapelera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMPapeleraActionPerformed(evt);
            }
        });
        editMenu.add(JMPapelera);

        menuBar.add(editMenu);

        jMenu1.setText("Gestion Producto");

        JMListadoP.setText("Listado");
        JMListadoP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMListadoPActionPerformed(evt);
            }
        });
        jMenu1.add(JMListadoP);

        menuBar.add(jMenu1);

        jMenu2.setText("Gestion Vendedor");

        JMListadoV.setText("Listado");
        JMListadoV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMListadoVActionPerformed(evt);
            }
        });
        jMenu2.add(JMListadoV);

        menuBar.add(jMenu2);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Help");
        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 695, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 533, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void editMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editMenuActionPerformed
            
    }//GEN-LAST:event_editMenuActionPerformed

    private void JMClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMClienteActionPerformed
        if(this.lisCliente!=null){
           this.lisCliente.dispose();
        }
        if(this.lisRestaurar != null){
            this.lisRestaurar.dispose();
        }
        try {
            this.gstCliente = new JIFGestionCliente();
            this.desktopPane.add(gstCliente);
            gstCliente.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(MDI_Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_JMClienteActionPerformed

    
    private void FMExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FMExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_FMExitActionPerformed

    private void JMListadoCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMListadoCActionPerformed
        if(this.lisRestaurar!=null){
           this.lisRestaurar.dispose();
           
        }
        if(this.gstCliente!=null){
            this.gstCliente.dispose();
        }
        try{
            this.lisCliente = new JIFListadoCliente();
        
            this.desktopPane.add(lisCliente);
            lisCliente.setVisible(true);
        }catch(Exception e){
            System.out.println("ERROR: " + e.getMessage());
        }
    }//GEN-LAST:event_JMListadoCActionPerformed

    private void JMPapeleraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMPapeleraActionPerformed
        if(this.lisCliente!=null){
           this.lisCliente.dispose();
        }
        
        if( this.gstCliente!=null){
           this.gstCliente.dispose(); 
        }
        try{
            this.lisRestaurar = new JIFPapeleraEliminados();
            this.desktopPane.add(lisRestaurar);
            lisRestaurar.setVisible(true);
        }catch(Exception e){
            System.out.println("ERROR: " + e.getMessage());
        }
    }//GEN-LAST:event_JMPapeleraActionPerformed

    private void JMListadoPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMListadoPActionPerformed
        try {
            JIFListadoProducto ListP = new JIFListadoProducto();
            this.desktopPane.add(ListP);
            ListP.setVisible(true);
        } catch (Exception e) {
             System.out.println("ERROR: " + e.getMessage());
        }
    }//GEN-LAST:event_JMListadoPActionPerformed

    private void JMListadoVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMListadoVActionPerformed
        try {
            JIFListadoVendedor ListV = new JIFListadoVendedor();
            this.desktopPane.add(ListV);
            ListV.setVisible(true);
        } catch (Exception e) {
             System.out.println("ERROR: " + e.getMessage());
        }
    }//GEN-LAST:event_JMListadoVActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MDI_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MDI_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MDI_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MDI_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MDI_Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu FMExit;
    private javax.swing.JMenuItem JMCliente;
    private javax.swing.JMenuItem JMListadoC;
    private javax.swing.JMenuItem JMListadoP;
    private javax.swing.JMenuItem JMListadoV;
    private javax.swing.JMenuItem JMPapelera;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar menuBar;
    // End of variables declaration//GEN-END:variables
    
    private void testconectar() {
      try{
          Conexion c = new Conexion();
          c.conectar();
      }catch (Exception e){
          System.out.println("ERROR: " + e.getMessage());
      }
    }
}
